# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_satisfaction_by11st',
            field=models.IntegerField(default=0),
        ),
    ]
