# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_product_product_satisfaction_by11st'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='review',
            field=models.TextField(default='', max_length=500),
        ),
    ]
